linters:
  enable-all: false
  enable:
    - errcheck
    - govet
    - ineffassign
    - typecheck
    - dupl
    - goconst
    - gofmt
    - unconvert
    - revive
    - staticcheck
    - gosimple
    - unused

issues:
  max-same-issues: 0

  exclude-rules:
    - path: _test.go
      linters:
        - revive
      text: "unused-parameter:"
