name: power-logger
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v1
        with:
          go-version: 1.22
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.3
          $(go env GOPATH)/bin/golangci-lint run -v

      - name: Run tests
        run: make test

      - name: Build-All
        run: make build-all

      - name: Archive binaries
        uses: actions/upload-artifact@v1
        with:
          name: bin
          path: bin